python-lib: simplify version editing for feature publishing

diff --git a/python-lib/publish/action.yml b/python-lib/publish/action.yml
--- a/python-lib/publish/action.yml
+++ b/python-lib/publish/action.yml
@@ -34,17 +34,15 @@ runs:
         FULL_ACCESS_TOKEN: ${{ env.PYPI_FULL_ACCESS_TOKEN }}
     - name: Set env vars
       run: |
-        publish_feature="false"
         if [[ -n "${{ steps.fury.outputs.next-feature-tag }}" ]];
-          if [[ $(grep -E '__version__ = ".+"' setup.py) ]]; then
+          if [[ $(grep -E ' +version=".+",' setup.py | wc -l) == 1 ]]; then
             echo "Temporarily updating version with feature tag ${{ steps.fury.outputs.next-feature-tag }}."
-            sed -i 's/__version__ = "\(.\+\)"/__version__ = "\1${{ steps.fury.outputs.next-feature-tag }}"/' setup.py
-            publish_feature="true"
+            sed -i 's/\( \+\)version="\(.\+\)",/\1version="\2${{ steps.fury.outputs.next-feature-tag }}",/' setup.py
           else
-            echo "Can't find __version__ to update, skipping feature publish."
+            echo "Can't find a version to update in setup.py"
+            exit 1
           fi
         fi
-        echo "PUBLISH_FEATURE=${publish_feature}" >> $GITHUB_ENV
         echo "RELEASE_NAME=$(python setup.py --fullname)" >> $GITHUB_ENV
       shell: bash
     - name: Create Release
@@ -55,12 +53,14 @@ runs:
       with:
         tag_name: ${{ env.RELEASE_NAME }}
         release_name: ${{ env.RELEASE_NAME }}
+    - name: Build dist
+      run: python setup.py sdist
+      shell: bash
     - name: Push to GemFury
-      if: ${{ inputs.public == 'false' && github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/main') || env.PUBLISH_FEATURE == 'true') }}
+      if: ${{ inputs.public == 'false' && github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/main') || steps.fury.outputs.next-feature-tag != '' }}
       uses: LedgerHQ/actions/gemfury/publish
       env:
-        DEPLOY_TOKEN: ${{ env.PYPI_PUSH_TOKEN || env.PYPI_FULL_ACCESS_TOKEN }}
-      shell: bash
+        PUSH_TOKEN: ${{ env.PYPI_PUSH_TOKEN || env.PYPI_FULL_ACCESS_TOKEN }}
     - name: Push to Pypi
       if: ${{ inputs.public == 'true' && startsWith(github.ref, 'refs/heads/main') && github.event_name == 'push' }}
       env:
