fix: indent errors

diff --git a/pdm/doc/build/action.yml b/pdm/doc/build/action.yml
--- a/pdm/doc/build/action.yml
+++ b/pdm/doc/build/action.yml
@@ -35,118 +35,118 @@ inputs:
 runs:
   using: composite
   steps:
-  - name: Clone and install dependencies
-    uses: LedgerHQ/actions/pdm/init@main
-    id: init
-    if: inputs.init == 'true'
-    with:
-      group: ${{ inputs.group }}
-      exclude-group: ${{ inputs.exclude-group }}
-      history: true
-      pypi-token: ${{ inputs.pypi-token }}
-      python-version: ${{ inputs.python-version }}
+    - name: Clone and install dependencies
+      uses: LedgerHQ/actions/pdm/init@main
+      id: init
+      if: inputs.init == 'true'
+      with:
+        group: ${{ inputs.group }}
+        exclude-group: ${{ inputs.exclude-group }}
+        history: true
+        pypi-token: ${{ inputs.pypi-token }}
+        python-version: ${{ inputs.python-version }}
 
-  - name: Update the CHANGELOG
-    # Failsafe changelog to avoid failure when there is no update
-    run: |
-      pdm changelog || true
-    env:
-      FORCE_COLOR: 'true'
-    shell: bash
+    - name: Update the CHANGELOG
+      # Failsafe changelog to avoid failure when there is no update
+      run: |
+        pdm changelog || true
+      env:
+        FORCE_COLOR: 'true'
+      shell: bash
 
-  - name: Upload the CHANGELOG
-    uses: actions/upload-artifact@v4
-    with:
-      name: changelog
-      path: CHANGELOG.md
+    - name: Upload the CHANGELOG
+      uses: actions/upload-artifact@v4
+      with:
+        name: changelog
+        path: CHANGELOG.md
 
-  - name: Download provided OpenAPI artifact
-    if: inputs.openapi != 'true' && inputs.openapi != 'false'
-    continue-on-error: true
-    uses: actions/download-artifact@v4
-    with:
-      name: ${{ inputs.openapi }}
-      path: docs
+    - name: Download provided OpenAPI artifact
+      if: inputs.openapi != 'true' && inputs.openapi != 'false'
+      continue-on-error: true
+      uses: actions/download-artifact@v4
+      with:
+        name: ${{ inputs.openapi }}
+        path: docs
 
-  - name: Generate OpenAPI specs (fallback)
-    if: inputs.openapi == 'true'
-    run: |
-      pdm doc:openapi
-    env:
-      FORCE_COLOR: "true"
-    shell: bash
+    - name: Generate OpenAPI specs (fallback)
+      if: inputs.openapi == 'true'
+      run: |
+        pdm doc:openapi
+      env:
+        FORCE_COLOR: "true"
+      shell: bash
 
-  - name: Upload OpenAPI specs (fallback)
-    if: inputs.openapi == 'true'
-    uses: actions/upload-artifact@v4
-    with:
-      name: openapi
-      path: docs/openapi.yaml
+    - name: Upload OpenAPI specs (fallback)
+      if: inputs.openapi == 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: openapi
+        path: docs/openapi.yaml
 
-  - name: Generate the documentation
-    if: inputs.site == 'true'
-    run: |
-      pdm doc:build
-    env:
-      FORCE_COLOR: 'true'
-    shell: bash
+    - name: Generate the documentation
+      if: inputs.site == 'true'
+      run: |
+        pdm doc:build
+      env:
+        FORCE_COLOR: 'true'
+      shell: bash
 
-  - name: Upload the generated documentation
-    if: inputs.site == 'true'
-    uses: actions/upload-artifact@v4
-    with:
-      name: documentation
-      path: site/
-      retention-days: 7
-      if-no-files-found: error
+    - name: Upload the generated documentation
+      if: inputs.site == 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: documentation
+        path: site/
+        retention-days: 7
+        if-no-files-found: error
 
-  - name: Move current OpenAPI specs
-    if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
-    continue-on-error: true
-    run: |
-      mv docs/openapi.yaml openapi.head.yaml
-    shell: bash
+    - name: Move current OpenAPI specs
+      if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
+      continue-on-error: true
+      run: |
+        mv docs/openapi.yaml openapi.head.yaml
+      shell: bash
 
-  - name: Checkout base ref
-    id: checkout-base
-    if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
-    continue-on-error: true
-    run: |
-      CURRENT_REF=$(git rev-parse HEAD)
-      echo "backup-ref=${CURRENT_REF}" >> $GITHUB_OUTPUT
+    - name: Checkout base ref
+      id: checkout-base
+      if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
+      continue-on-error: true
+      run: |
+        CURRENT_REF=$(git rev-parse HEAD)
+        echo "backup-ref=${CURRENT_REF}" >> $GITHUB_OUTPUT
 
-      git restore .
-      git checkout ${{ github.base_ref }}
-    shell: bash
+        git restore .
+        git checkout ${{ github.base_ref }}
+      shell: bash
 
-  - name: Synchronize dependencies (base ref)
-    if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
-    continue-on-error: true
-    run: |
-      pdm sync
-    shell: bash
+    - name: Synchronize dependencies (base ref)
+      if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
+      continue-on-error: true
+      run: |
+        pdm sync
+      shell: bash
 
-  - name: Generate base OpenAPI specs
-    if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
-    continue-on-error: true
-    run: |
-      pdm doc:openapi
-    env:
-      FORCE_COLOR: 'true'
-    shell: bash
+    - name: Generate base OpenAPI specs
+      if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
+      continue-on-error: true
+      run: |
+        pdm doc:openapi
+      env:
+        FORCE_COLOR: 'true'
+      shell: bash
 
-  - name: Move base OpenAPI specs
-    if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
-    continue-on-error: true
-    run: |
-      mv docs/openapi.yaml openapi.base.yaml
-    shell: bash
+    - name: Move base OpenAPI specs
+      if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
+      continue-on-error: true
+      run: |
+        mv docs/openapi.yaml openapi.base.yaml
+      shell: bash
 
-  - name: Generate the OpenAPI diff
-    if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
-    continue-on-error: true
-    uses: LedgerHQ/actions/openapi/diff@main
-    with:
-      base: openapi.base.yaml
-      head: openapi.head.yaml
-      github-token: ${{ inputs.github-token }}
+    - name: Generate the OpenAPI diff
+      if: success() && steps.init.outputs.is_pr == 'true' && inputs.openapi == 'true'
+      continue-on-error: true
+      uses: LedgerHQ/actions/openapi/diff@main
+      with:
+        base: openapi.base.yaml
+        head: openapi.head.yaml
+        github-token: ${{ inputs.github-token }}
